1

In [1]:
import numpy as np
def sigmoid(x):
    # ф-я активации: f(x) = 1 / (1 + e^(-x))
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

import numpy as np
class OurNeuralNetwork1:
    '''
    Данные нейросети:
        - три входа
        - три нейрона в скрытых слоях (h1, h2, h3)
        - выход (o1)
    Нейроны имеют идентичные веса и пороги:
        - w = [0.5, 0.5, 0.5]
        - b = 0
    '''
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        
        # Класс Neuron из предыдущего раздела
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        
        # Входы для o1 - это выходы h1, h2, h3
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

network = OurNeuralNetwork1()
x = np.array([0, 10, 100])
print(network.feedforward(x))

0.8175744761936437


1.2.1 Sigmoid

In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.8151036049051821


1.2.2 Tanh

In [3]:
import numpy as np

def tanh(x):
    return np.tanh(x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanh(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.9050813365686774


1.2.3 ReLU

In [4]:
#Задание №1.2.3
#ReLU
import numpy as np

def ReLU(x):
    return max(0.0, x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return ReLU(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

6.75


2.1

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

url = r'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
dataset = pd.read_csv(url)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.80, test_size = 0.20, stratify = Y, random_state = 123)

mlp_classifier = MLPClassifier(max_iter = 1000).fit(X_train, Y_train)
Y_pred = mlp_classifier.predict(X_test)

df = pd.DataFrame({'Actual': Y_test, 'Predicted': Y_pred})
print(df)

print("\nTest Accuracy: %.3f"%mlp_classifier.score(X_test, Y_test))
print('Training Accuracy: %.3f'%mlp_classifier.score(X_train, Y_train))
print(f"\nMatrix of Confusion:\n {confusion_matrix(Y_test, Y_pred)}")
print(f"\nLoss : ", mlp_classifier.loss_)
print(f'Number of Coefs : ', len(mlp_classifier.coefs_))
print(f'Number of Intercepts : ', len(mlp_classifier.intercepts_))
print(f'Number of Iterations for Which Estimator Run : ', mlp_classifier.n_iter_)
print(f'Name of Output Layer Activation Function : ', mlp_classifier.out_activation_)

C:\Users\mmyty\AppData\Local\Temp\ipykernel_21584\3005220023.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


        Actual   Predicted
0   Versicolor  Versicolor
1       Setosa      Setosa
2    Virginica   Virginica
3    Virginica   Virginica
4       Setosa      Setosa
5       Setosa      Setosa
6    Virginica   Virginica
7   Versicolor   Virginica
8    Virginica   Virginica
9       Setosa      Setosa
10      Setosa      Setosa
11  Versicolor  Versicolor
12   Virginica   Virginica
13  Versicolor  Versicolor
14   Virginica   Virginica
15  Versicolor  Versicolor
16      Setosa      Setosa
17      Setosa      Setosa
18      Setosa      Setosa
19      Setosa      Setosa
20      Setosa      Setosa
21   Virginica   Virginica
22   Virginica   Virginica
23  Versicolor  Versicolor
24   Virginica   Virginica
25   Virginica   Virginica
26  Versicolor  Versicolor
27  Versicolor  Versicolor
28  Versicolor   Virginica
29  Versicolor  Versicolor

Test Accuracy: 0.933
Training Accuracy: 0.992

Matrix of Confusion:
 [[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]

Loss :  0.05625574952443364
Number of Coefs :  2
Number

2.2

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

url = r'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'
data = pd.read_csv(url)
#print(dataset.head())

X = data.iloc[:, :-1].values
y = data.iloc[:, 1].values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
mlp = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

#Оценка качества модели:
from sklearn.metrics import mean_squared_error, r2_score

print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("R2 score: %.2f" % r2_score(y_test, y_pred))

#Получение информации о количестве слоев и нейронов в каждом слое:
print(mlp.n_layers_) # количество слоев
print(mlp.hidden_layer_sizes) # количество нейронов в каждом скрытом слое
#Получение значения весов и смещений для каждого слоя: 
print(mlp.coefs_)

Mean squared error: 706984608.62
R2 score: 0.35
4
(100, 50)
[array([[ 1.51559623e+00, -3.31340045e-25,  1.71242379e+00,
         1.77566056e+00,  1.91818871e+00,  1.53609465e+00,
        -6.99750518e-18, -1.65933942e-06,  1.79056233e+00,
         1.87163426e+00, -6.95703303e-25,  1.88367466e+00,
         1.52925110e+00,  1.76522856e+00,  1.60427255e+00,
        -3.86110236e-10, -1.32579797e-07,  1.81095053e+00,
         1.55256218e+00,  1.83469265e+00,  2.57430977e-02,
         1.91943347e+00,  5.35944241e-26, -8.78279876e-18,
        -2.22811333e-06,  1.61567276e+00,  1.74486053e+00,
        -1.16682595e-01,  1.52584565e+00,  1.90001125e+00,
         1.57096074e-23,  1.87073950e+00, -5.14847554e-02,
         1.66621049e+00,  1.85384511e+00, -7.51685204e-05,
         1.58991569e+00, -5.00362737e-02, -9.75103538e-02,
         1.67827953e+00,  1.73761958e+00,  1.80966387e+00,
         1.66980840e+00,  1.45087806e+00,  1.86663548e+00,
         4.66911030e-20,  1.90778150e+00,  1.83261142e

c:\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
