In [3]:
import numpy as np
# import random

1.3.1

In [ ]:
arr = np.zeros(8*8)
arr = arr.reshape(8,8)
for i in range(8):
    for j in range(8):
        if(i%2 == 0 and j % 2 == 1 or i %2 == 1 and j %2 == 0):
            arr[i][j] = 1
print(arr)         

1.3.2

In [22]:
arr = np.tile(np.arange(5), (5, 1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3

In [23]:
arr = np.random.rand(3,3,3)
print(arr)

[[[0.00360889 0.13526481 0.58133883]
  [0.84724414 0.65713692 0.0445369 ]
  [0.12996992 0.24544685 0.45506669]]

 [[0.19374794 0.46773179 0.31386069]
  [0.13358952 0.34311066 0.07347142]
  [0.69208132 0.35260266 0.61404247]]

 [[0.57084241 0.50209337 0.86868636]
  [0.92131004 0.89087852 0.52930933]
  [0.64119237 0.84830326 0.32023841]]]


1.3.4

In [59]:
n = 10
arr = np.ones((n,n))
for i in range(n):
    for j in range(n):
        if(i >0 and j > 0 and i < n-1 and j < n-1): arr[i][j] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.3.5

In [62]:
arr = np.array([345, 675, 24, 76, 32])
arr = np.sort(arr)
print(arr[::-1])

[675 345  76  32  24]


1.3.6

In [ ]:
arr = np.array([345, 675, 24, 76, 32])
